
# LLM Model IDs
OLLAMA_MODEL_ID: "llama3.2:3b" # 3B parameter model

# Dataset paths
DATASET_PATH: ../data/collection_with_abstracts.csv

DATASET_LIMIT: 120

# Test dataset path
TEST_DATASET_PATH: ../../data/test_collection_with_abstracts.xlsx

# Evaluation dataset path
EVALUATION_DATASET_PATH: ../../data/eval_collection_with_abstracts.xlsx

# Model hyperparameters
SPACY_MODEL: en_core_web_lg

# LLM Model hyperparameters
TRANSFORMER_MODEL: all-MiniLM-L6-v2
