
# LLM Model IDs
OLLAMA_MODEL_ID: "llama3.2:3b"

# Dataset paths
DATASET_PATH: ../data/collection_with_abstracts.csv

DATASET_LIMIT: 0 # 0 for no limit

# Test dataset path
TEST_DATASET_PATH: ../../data/test_collection_with_abstracts_and_labels.xlsx

# Evaluation dataset path
EVALUATION_DATASET_PATH: ../../data/eval_collection_with_abstracts.xlsx

# Results dataset paths
RESULTS_RELEVANT_DATASET_PATH: ../data/files/relevant_papers.xlsx
RESULTS_IRRELEVANT_DATASET_PATH: ../data/files/filtered_out_papers.xlsx

# Model hyperparameters
SPACY_MODEL: en_core_web_lg

# LLM Model hyperparameters
TRANSFORMER_MODEL: all-MiniLM-L6-v2 # all-mpnet-base-v2, all-MiniLM-L6-v2
