from typing import Dict, Set, List


class Constants:
    # enum for topics
    TOPICS = {
        'text_mining': 'text_mining',
        "computer_vision": "computer_vision",
        'both': 'both',
        'other': 'other'
    }

    # Medical terms to exclude/disambiguate
    MEDICAL_TERMS: Set[str] = {
        'computer vision syndrome',
        'cvs-q',
        'digital eye strain',
        'eye strain',
        'epidemiological',
        'epidemiological data',
        'visual health',
        'visual symptoms',
        'visual fatigue',
        'visual stress',
        'visual discomfort',
        'ocular surface',
        'ophthalmology',
        'optometry',
        'eye disease',
        'retina',
        'glaucoma',
        'cataract',
        'epidemiological study',
        'clinical trial',
        'virus transmission',
        'vaccination',
        'vaccine development',
        'cell',
        'immunology',
        'pathogen',
        'infectious disease',
        'tumor',
        'healthcare',
        'transcriptomics',
    }

    NEGATIVE_KEYWORDS = [
        'urban planning', 'building design',
        'households', 'residential buildings', 'urban planners', 'smart cities', 'sustainable cities',
        'policymakers', 'external shading', 'operable window types',
        'Google Street View', 'demographic characteristics',
        'forest',
    ]

    # Method classification patterns with type hints
    METHOD_PATTERNS: Dict[str, Set[str]] = {
        'text_mining': {
            'nlp',
            'text mining',
            'natural language processing',
            'text analysis',
            'named entity recognition',
            'sentiment analysis',
            'text classification',
            'language model',
            'word embedding',
            'document classification',
            'topic modeling',
            'text extraction',
            'text generation',
            'textual metadata',
            'report Generation',
            'question Answering',
            'summarization',
            'text summarization',
            'information extraction',
            'text understanding',
            'content analysis',
            'post analysis',
            'comments',
            'engagement analysis',
            'social media',
            'posts',
            'biomarkers',
            'gene network analysis',
            'network structural information',
            'clinical notes',
            'clinical data',
            'clinical text',
            'medical records',
            'genomic sequence',
            'clinical text analysis',
            'genetic analysis',
            'gene expression',
            'variant analysis',
            'mutation detection',
            'phenotype analysis',
            'infodemiology',
        },
        'computer_vision': {
            'classification',
            'computer vision',
            'computer-aided vision',
            'detection',
            'detection strategy',
            'detection model',
            'image',
            'imaging',
            'image processing',
            'image processing model',
            'image analysis',
            'image detection',
            'image recognition',
            'image identification',
            'image classification',
            'image segmentation',
            'image generation',
            'image harmonization',
            'image area',
            'object detection',
            'segmentation',
            'spatial inference',
            'scene understanding',
            'vision-language',
            'vision-language model',
            'visual analysis',
            'visual inspection',
            'visual recognition',
            'visual pattern recognition',
            'visual Question Answering',
            'multi-layer image',
            'convolutional neural network',
            'ct scan',
            'mri',
            'x-ray',
            'microscopy image',
            'histopathology image',
            'medical image',
            'lesion detection',
            'lesion segmentation',
            'lesion classification',
            'lesion identification',
            'lesion analysis',
            'lesion recognition',
            'lesion localization',
            'tumor detection',
            'tumor segmentation',
            'tumor classification',
            'tumor identification',
            'tumor analysis',
            'cell detection',
            'cell counting',
        }
    }

    # Define semantic patterns for deep learning with type hints
    DL_PATTERNS: Dict[str, List[str]] = {
        'architecture': [
            'ai model',
            'artificial intelligence',
            'artificial neural network',
            'attention mechanism',
            'autoencoder',
            'alexnet',

            'bert',

            'capsule network',
            'convolutional neural network',
            'cnn',

            'deep learning',
            'deep-learning',
            'deep neural',
            'decoder',
            'encoder',
            'encoder-decoder',
            'efficientnet',

            'foundation model',
            'feedforward neural network',

            'gan',
            'gpt',
            'gru',
            'gnn',
            'generative adversarial network',
            'graph neural network',
            'graph convolutional network',

            'inceptionv3',
            'inception',
            'inception network',

            'lstm',
            'language model',
            'long short-term memory',

            'machine learning',
            'neural network',
            'neural architecture',

            'pre-trained model',
            'pre-trained network',
            'pre-trained architecture',

            'rnn',
            'r-cnn',
            'residual network',
            'recurrent neural network',
            'resnet',

            'transformer',
            'transformer-based model',
            'transformer model',
            'transformer architecture',
            'transformer network',

            'self-attention',
            'self-attention mechanism',
            'self-attention layer',
            'seq2seq',

            'u-net',
            'unet',
            'unet++',
            'unetr++',

            'variational autoencoder',
            'vgg',
            'vision transformer',
            'visual transformer',
            'vision-language model',
            'vae',

            'word embedding',
            'word2vec',

            'yolo',
        ],
        'task': [
            'classification',
            'detection',
            'detect',
            'prediction',
            'recognition',
            'segmentation',
            'generation',
            'identification',
            'image identification',
            'forecasting',
            'clustering',
            'feature extraction',
            'pattern recognition',
            'anomaly detection',
            'automated detection',
            'automated recognition',
            'automated identification',
            'sequence prediction',
            'mutation detection',
            'strain classification',
            'outbreak prediction',
            'genomic analysis',
        ],
        'context': [
            'model training',
            'feature learning',
            'data augmentation',
            'transfer learning',
            'layer',
            'network',
            'deep',
            'inference',
            'supervised',
            'unsupervised',
            'fine-tuning',
            'embedding',
            'backpropagation',
            'gradient descent',
            'multimodal',
        ]
    }

    # Scoring weights
    WEIGHTS: Dict[str, float] = {
        'architecture': 0.6,
        'task': 0.3,
        'context': 0.1
    }

    # Method indicators with weights
    METHOD_INDICATORS: Dict[str, float] = {
        "using": 1.5,
        "based on": 2.0,
        "through": 1.0,
        "implements": 2.0,
        "applying": 1.5,
        "utilizing": 1.5,
        "featuring": 1.0,
        "incorporating": 1.5
    }

    # Domain-specific sentences for semantic similarity
    DOMAIN_SENTENCES = [
        "We study the spread of infectious diseases using computational models.",
        "Our research focuses on viral genomics and epidemiology.",
        "The paper analyzes epidemiological data to predict disease outbreaks.",
        "We develop computational methods for virology research.",
        "Our study applies machine learning to understand virus-host interactions.",
        "We use bioinformatics tools to analyze viral sequences.",
        "The research involves modeling the transmission dynamics of viruses.",
        "We apply deep learning to detect viral infections from medical images.",
        "Our work focuses on vaccine development and efficacy prediction.",
        "We analyze epidemiological trends in infectious diseases.",
        "This study investigates the epidemiology of viral diseases.",
        "We explore the genetic diversity of viral pathogens.",
        "Our research aims to predict pandemic spread using machine learning.",
        "We utilize computational biology to study virus evolution.",
        "The study models the impact of interventions on disease transmission.",
        "Epidemiological models benefit from deep learning techniques to forecast disease outbreaks.",
        "Virology research leverages AI to analyze viral genome data.",
        "Public health initiatives use machine learning for real-time disease surveillance.",
        "Us a fully-automated artificial intelligence algorithm to detect from CT scans.",
        "AI-based quantitative image analysis of screening CTs in osteoporosis screening"
    ]

    # Define deep learning-related sentences for semantic similarity
    DL_SENTENCES = [
        "Deep learning models are used to classify viral sequences in genomic studies.",
        "We utilize machine learning to predict epidemic trends based on historical data.",
        "Our approach applies neural networks to detect viral mutations from sequence data.",
        "The study employs deep learning for automated detection of viral infections in medical images.",

        # General Deep Learning Applications
        "This study utilizes deep learning techniques to analyze medical data.",
        "We apply neural networks to predict disease outcomes.",
        "A convolutional neural network is developed for image classification tasks.",
        "Our research employs recurrent neural networks for time-series analysis.",
        "The model is based on transformer architecture for natural language processing.",
        "We implement deep learning algorithms to improve diagnostic accuracy.",
        "A deep neural network is trained to identify patterns in genomic data.",
        "Our approach leverages machine learning methods for predictive modeling.",
        "We use unsupervised learning to discover hidden structures in the data.",
        "The research focuses on supervised learning for classification problems.",
        "We introduce an attention mechanism to enhance model performance.",
        "Our method involves transfer learning to utilize pre-trained models.",
        "We adopt a generative adversarial network for data augmentation.",
        "The study applies autoencoders for feature extraction and dimensionality reduction.",
        "We propose a novel deep learning framework for medical image segmentation.",
        "Our system integrates reinforcement learning for decision-making processes.",
        "We utilize graph neural networks to model complex relationships in data.",
        "The deep learning model is optimized using backpropagation and gradient descent.",
        "We employ deep belief networks for hierarchical feature learning.",
        "The study uses ensemble learning to improve prediction accuracy.",

        # Applications in Virology and Epidemiology
        "Deep learning techniques are applied to predict viral mutations.",
        "We use neural networks to model the spread of infectious diseases.",
        "A machine learning approach is used for epidemic forecasting.",
        "Our study employs convolutional neural networks to detect COVID-19 from CT scans.",
        "We analyze genomic sequences using deep learning methods.",
        "The research applies recurrent neural networks to predict infection rates.",
        "We develop a transformer-based model for virus classification.",
        "Our model identifies potential antiviral compounds using deep learning.",
        "We utilize deep learning for automated contact tracing analysis.",
        "The study employs machine learning to understand virus-host interactions.",
        "We implement a deep learning framework to analyze social media data for outbreak detection.",
        "Our approach uses deep learning to predict vaccine efficacy.",
        "We apply unsupervised learning to cluster viral genome sequences.",
        "The model uses attention mechanisms to focus on key genomic features.",
        "We leverage deep learning for protein structure prediction in viruses.",
        "Our system detects zoonotic spillover events using machine learning.",
        "We utilize graph convolutional networks to model transmission networks.",
        "Deep learning models are trained to predict drug resistance mutations.",
        "We use deep neural networks to classify pathogens from metagenomic data.",
        "Our research employs deep learning for phylogenetic analysis.",

        # Deep Learning in Microbiology and Microscopy
        "We apply deep learning techniques to analyze microscopy images for bacterial detection.",
        "A convolutional neural network is developed for identification of bacteria in microscopy images.",
        "Our research employs deep learning to enhance detection of pathogens in clinical samples.",
        "We implement CNN-based algorithms for quantification of bacterial cells using dark field microscopy.",
        "The study utilizes AI-enabled analytics to improve detection specificity in microbiological diagnostics.",
        "We use deep learning-powered computer vision to identify microorganisms in complex samples.",
        "Our approach integrates image processing models with deep learning for pathogen detection.",
        "We employ deep learning methods to analyze dark field microscopy images for bacterial identification.",
        "The research focuses on using neural networks for rapid detection of foodborne pathogens.",
        "We develop a deep learning framework for precise identification and quantification of bacterial cells.",

        # Medical Imaging and Computer Vision Applications
        "A convolutional neural network is used for lesion segmentation in medical images.",
        "We develop a deep learning model for tumor detection in MRI scans.",
        "Our method applies deep learning to classify skin lesions from images.",
        "We employ deep learning for retinal image analysis in diabetic patients.",
        "The study uses deep neural networks for automated cancer diagnosis.",
        "We utilize U-Net architecture for medical image segmentation tasks.",
        "Our approach enhances image resolution using super-resolution techniques.",
        "We implement a deep learning model for organ segmentation in CT scans.",
        "The research applies deep learning for fracture detection in X-ray images.",
        "We develop a deep learning-based system for histopathological image analysis.",
        "Our model detects pneumonia from chest X-ray images using CNNs.",
        "We use deep learning to analyze ultrasound images for fetal health assessment.",
        "The study employs deep learning for brain tumor classification.",
        "We apply transfer learning to improve medical image classification.",
        "Our approach uses 3D convolutional neural networks for volumetric data analysis.",
        "We implement a deep learning model for blood vessel segmentation.",
        "The research uses deep learning to detect Alzheimer’s disease from PET scans.",
        "We utilize deep learning for automated detection of COVID-19 pneumonia.",
        "Our system classifies breast cancer subtypes using deep learning algorithms.",
        "We apply deep learning to analyze microscopy images for cellular analysis.",
        "AI-based quantitative image analysis of screening CTs in osteoporosis screening",

        # Natural Language Processing and Text Mining Applications
        "We use natural language processing to extract information from clinical notes.",
        "Our study applies deep learning for sentiment analysis of health-related tweets.",
        "We implement a transformer-based model for biomedical text classification.",
        "The research employs BERT for named entity recognition in medical documents.",
        "We utilize deep learning to summarize scientific articles automatically.",
        "Our approach uses deep learning for question answering on medical datasets.",
        "We develop a language model to predict adverse drug reactions.",
        "The study applies topic modeling to identify trends in health records.",
        "We use word embeddings to represent biomedical terminology.",
        "Our method leverages deep learning for automated coding of medical procedures.",
        "We implement deep learning for language translation in medical contexts.",
        "The research employs sequence-to-sequence models for report generation.",
        "We use deep learning to classify patient feedback for quality improvement.",
        "Our system detects misinformation in health-related social media posts.",
        "We apply sentiment analysis to assess public opinion on vaccination.",
        "Our model predicts disease outbreaks by analyzing news articles.",
        "We utilize deep learning for automated chart review and data extraction.",
        "The study employs deep learning for speech recognition in telemedicine.",
        "We develop a chatbot using deep learning for patient engagement.",
        "Our approach uses deep learning for optical character recognition of medical documents.",

        # Genomics and Bioinformatics Applications
        "We apply deep learning to predict gene expression levels.",
        "Our study uses deep neural networks for SNP classification.",
        "We develop a deep learning model for protein function prediction.",
        "The research employs deep learning for enhancer-promoter interaction prediction.",
        "We use convolutional neural networks to analyze DNA methylation data.",
        "Our method predicts transcription factor binding sites using deep learning.",
        "We utilize deep learning for splice site prediction in genomics.",
        "The study applies deep learning to identify non-coding RNAs.",
        "We implement deep learning for chromatin state segmentation.",
        "Our model predicts gene-disease associations using deep learning.",
        "We employ deep learning for de novo genome assembly.",
        "The research uses deep learning to analyze single-cell RNA sequencing data.",
        "We develop a deep learning framework for epigenetic landscape modeling.",
        "Our approach applies deep learning to metabolic pathway prediction.",
        "We use deep learning for phylogenetic tree reconstruction.",
        "The study utilizes deep learning for microbiome data classification.",
        "We implement deep learning to predict protein-ligand interactions.",
        "Our model identifies genetic variants associated with diseases using deep learning.",
        "We employ deep learning for genotype imputation in population genetics.",
        "Our research uses deep learning to analyze CRISPR off-target effects.",

        # Drug Discovery and Computational Chemistry Applications
        "We use deep learning to predict drug-target interactions.",
        "Our study develops a deep learning model for virtual screening of compounds.",
        "We implement deep learning for quantitative structure-activity relationship modeling.",
        "The research employs deep learning for molecular property prediction.",
        "We utilize deep generative models to design novel drug molecules.",
        "Our approach uses deep learning to predict pharmacokinetic properties.",
        "We apply deep learning for toxicity prediction of chemical compounds.",
        "The study uses deep learning to model protein folding.",
        "We develop a deep learning framework for predicting bioactivity of molecules.",
        "Our model identifies potential drug repurposing opportunities using deep learning.",
        "We employ deep learning for side effect prediction in drug development.",
        "The research applies deep learning to analyze high-throughput screening data.",
        "We use deep learning to optimize drug delivery systems.",
        "Our method predicts molecular docking scores using deep learning.",
        "We utilize deep learning for cheminformatics and compound classification.",
        "The study develops a deep learning model for ADMET property prediction.",
        "We implement deep learning to understand molecular dynamics simulations.",
        "Our approach uses deep learning for antibody design and optimization.",
        "We apply deep learning for predicting chemical reaction outcomes.",
        "Our research uses deep learning to analyze nanomaterials for biomedical applications.",

        # Other Relevant Applications
        "We develop a deep learning model for speech emotion recognition in therapy sessions.",
        "Our study applies deep learning to predict patient readmission rates.",
        "We use deep learning to analyze electronic health records for disease prediction.",
        "The research employs deep learning for personalized treatment recommendation.",
        "We implement deep learning for anomaly detection in healthcare data.",
        "Our approach uses deep learning to model patient survival rates.",
        "We utilize deep learning for optimizing healthcare logistics and resource allocation.",
        "The study applies deep learning to monitor patient vital signs remotely.",
        "We develop a deep learning framework for fraud detection in medical insurance claims.",
        "Our model predicts patient adherence to medication using deep learning.",
        "We employ deep learning for health risk assessment based on lifestyle data.",
        "The research uses deep learning to analyze genetic networks and interactions.",
        "We apply deep learning for disease subtype classification.",
        "Our method utilizes deep learning for multimodal data integration in healthcare.",
        "We implement deep learning for real-time health monitoring using wearable devices.",
        "The study employs deep learning to enhance telemedicine services.",
        "We use deep learning to predict surgical outcomes and complications.",
        "Our approach applies deep learning for health informatics and data mining.",
        "We utilize deep learning for patient stratification in clinical trials.",
        "Our research employs deep learning to model the spread of antimicrobial resistance.",

        # Statements Reflecting the Use of Deep Learning in Research
        "This paper presents a deep learning approach to solve the problem.",
        "We propose a neural network model that outperforms traditional methods.",
        "Our deep learning algorithm achieves state-of-the-art results.",
        "We conduct experiments using a deep learning framework.",
        "The results demonstrate the effectiveness of deep learning techniques.",
        "We explore the application of deep learning in this domain.",
        "Our study highlights the potential of deep neural networks.",
        "We compare various deep learning models in our experiments.",
        "The deep learning method shows significant improvement over baseline models.",
        "We investigate the impact of deep learning on data analysis.",
        "Our findings support the use of deep learning for this task.",
        "We validate our deep learning model on multiple datasets.",
        "The deep learning approach is integrated into our system.",
        "We discuss the challenges and solutions in deep learning implementation.",
        "Our work contributes to the field by introducing deep learning methods.",
        "We leverage deep learning to enhance the accuracy of predictions.",
        "The proposed model is based on deep learning architectures.",
        "We demonstrate how deep learning can be applied effectively.",
        "Our methodology involves training deep neural networks.",
        "We show that deep learning provides superior performance.",
    ]
